name: file_dattente
description: "Application de gestion de file d'attente intelligente."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (juste pour la connexion)
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  # Base de données locale
  sqflite: ^2.3.2
  path: ^1.9.0

  # QR Code
  qr_flutter: ^4.1.0

  # Notifications
  flutter_local_notifications: ^17.0.0

  # Gestion d'état
  provider: ^6.1.5+1

  # Génération d'identifiants uniques
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true